config/routes.rb
EatEnough::Application.routes.draw do
  resources :dishes

  get "pages/home"
  root to: "pages#home"

  resources :ingredients
  resources :dishes

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :name, :num_selected

  has_many :dish_ingredients
  has_many :ingredients, :through => :dish_ingredients
end

app/models/dish_ingredient.rb
class DishIngredient < ActiveRecord::Base
	attr_accessible :grams

  belongs_to :dish
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :calories, :carbohydrate, :fat, :name, :protein, :sodium, :sugar, :num_selected

  has_many :dish_ingredients
  has_many :dishes, :through => :dish_ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dishes/_form.html.haml
= simple_form_for @dish do |f|
  - if @dish.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dish.errors.count, "error")} prohibited this dish from being saved:"
      %ul
        - @dish.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :name
  .field
    = f.input :num_selected
  .fields
    = f.association :ingredients, as: :check_boxes


  .actions
    = f.submit 'Save'

app/views/dishes/edit.html.haml
%h1 Editing dish

= render 'form'

= link_to 'Show', @dish
\|
= link_to 'Back', dishes_path

app/views/dishes/index.html.haml
%h1 Listing dishes

%table
  %tr
    %th Name
    %th Num selected
    %th
    %th
    %th

  - @dishes.each do |dish|
    %tr
      %td= dish.name
      %td= dish.num_selected
      %td= link_to 'Show', dish
      %td= link_to 'Edit', edit_dish_path(dish)
      %td= link_to 'Destroy', dish, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dish', new_dish_path

app/views/dishes/new.html.haml
%h1 New dish

= render 'form'

= link_to 'Back', dishes_path

app/views/dishes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @dish.name
%p
  %b Num selected:
  = @dish.num_selected

%p
  %b Ingredients:
  %ul
    - @dish.ingredients.each do |ingredient|
      %li= ingredient.name



= link_to 'Edit', edit_dish_path(@dish)
\|
= link_to 'Back', dishes_path

app/views/ingredients/_form.html.haml
= form_for @ingredient do |f|
  - if @ingredient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:"
      %ul
        - @ingredient.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :calories
    = f.text_field :calories
  .field
    = f.label :fat
    = f.text_field :fat
  .field
    = f.label :protein
    = f.text_field :protein
  .field
    = f.label :sodium
    = f.text_field :sodium
  .field
    = f.label :sugar
    = f.text_field :sugar
  .field
    = f.label :carbohydrate
    = f.text_field :carbohydrate
  .field
    = f.label :num_selected
    = f.text_field :num_selected
  .actions
    = f.submit 'Save'

app/views/ingredients/edit.html.haml
%h1 Editing ingredient

= render 'form'

= link_to 'Show', @ingredient
\|
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1 Listing ingredients

%table
  %tr
    %th Name
    %th Calories
    %th Fat
    %th Protein
    %th Sodium
    %th Sugar
    %th Carbohydrate
    %th
    %th
    %th

  - @ingredients.each do |ingredient|
    %tr
      %td= ingredient.name
      %td= ingredient.calories
      %td= ingredient.fat
      %td= ingredient.protein
      %td= ingredient.sodium
      %td= ingredient.sugar
      %td= ingredient.carbohydrate
      %td= link_to 'Show', ingredient
      %td= link_to 'Edit', edit_ingredient_path(ingredient)
      %td= link_to 'Destroy', ingredient, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ingredient', new_ingredient_path

app/views/ingredients/new.html.haml
%h1 New ingredient

= render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ingredient.name
%p
  %b Calories:
  = @ingredient.calories
%p
  %b Fat:
  = @ingredient.fat
%p
  %b Protein:
  = @ingredient.protein
%p
  %b Sodium:
  = @ingredient.sodium
%p
  %b Sugar:
  = @ingredient.sugar
%p
  %b Carbohydrate:
  = @ingredient.carbohydrate

= link_to 'Edit', edit_ingredient_path(@ingredient)
\|
= link_to 'Back', ingredients_path

app/views/layouts/application.html.haml
!!!
%html{ 'ng-app' => "EatSome"}
	%head
		%title Eat Some
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		.navbar.navbar-inverse.navbar-fixed-top{ role: "navigation"}
			.container
				.navbar-header
					%button{type: "button", class: "navbar-toggle", data: {toggle: "collapse", target: ".navbar-collapse"}}
					%a.navbar-brand Eat Some
				.collapse.navbar-collapse
					%ul.nav.navbar-nav
						%li.active
							= link_to "Home", "#"
						%li
							= link_to "About", "#"
						%li
							= link_to "Contact", "#"
	%body
		.container
			= yield

app/views/pages/home.html.haml
.starter-tempate{ 'ng-controller' => 'AppCtrl'}

	#page-title.panel.panel-default
		%h1 Welcome to Eat Some
		%p.lead Your one stop shop for healthy nutrition

	%h2 Parameters:
	%span Total calories
	%input{'ng-model' => 'totalCalories' }
	%span Weight
	%input{'ng-model' => 'weight' }

	%h2 Recommendations:
	%p
		%span Carbs: {{recommendedValues.carbohydrate()}}
	%p
		%span Protein:  {{recommendedValues.protein()}}

	%h4 Select from list of ingredients:
	%ul#ingredient-list
		%li{ 'ng-repeat' => 'ingredient in visibleIngredients()', class: "{{sizeClass(ingredient.num_selected)}}", 'ng-click' => 'addToChosen(ingredient)'}
			{{ingredient.name}}

	%h4 Select from list of dishes:
	%ul#dish-list
		%li{ 'ng-repeat' => 'dish in visibleDishes()', class: "{{sizeClass(dish.num_selected)}}",'ng-click' => 'addToChosen(dish)'}
			{{dish.name}}

	%ul#chosen-list.well
		%li{ 'ng-repeat' => 'item in chosenItems'}
			{{item.name}}